name: Lint
on:
  push:
    paths:
      - 'linux-cachyos/PKGBUILD'
      - '.github/workflows/lint.yml'
  workflow_dispatch:
jobs:
  linux-cachyos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      id: makepkg
      uses: CachyOS/pkgbuild-action@master
      with:
        envvars: "_use_auto_optimization= _processor_opt=generic _cc_harder="
        pkgdir: "linux-cachyos"
        namcapExcludeRules: "invalidstartdir"
        makepkgArgs: "--skippgpcheck --noconfirm -s --nobuild"
